name: motor-fault-classification
channels:
  - conda-forge
dependencies:
  - python=3.8.8
  - numpy=1.20.2
  - pandas=1.2.3
  - keras=2.4.3
  - matplotlib=3.4.1
  - scikit-learn=0.24.2
  - scipy=1.6.3
